# **Diplomatura en Ciencia de Datos, Aprendizaje Automático y sus Aplicaciones**

## **Edición 2026**


----

# Trabajo práctico entregable - parte 1

Trabajaremos con la base de datos de `melb_data` presentada a continuación.

In [1]:
import matplotlib.pyplot as plt
import numpy
import pandas
import seaborn
seaborn.set_context('talk')

In [2]:
# Cargamos los datos
melb_df = pandas.read_csv(
    'https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/melb_data.csv')
melb_df[:3]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0

### Información acerca de las variables
Suburb: Suburb

Address: Dirección

Rooms: Número de habitaciones

Price: Precio en dólares australianos

Method:
S - propiedad vendida;
SP - propiedad vendida previamente;
PI - propiedad no vendida (pasó en subasta sin alcanzar el precio de reserva);
PN - vendida previamente no divulgada;
SN - vendida no divulgada;
NB - sin oferta;
VB - oferta del vendedor;
W - retirada antes de la subasta;
SA - vendida después de la subasta;
SS - vendida después de la subasta (precio no divulgado).
N/A - precio o oferta más alta no disponible.

Type:
br - dormitorio(s);
h - casa, cabaña, villa, semi-adosado, terraza;
u - unidad, dúplex;
t - casa adosada;
dev site - sitio de desarrollo;
o res - otra residencia.

SellerG: Agente inmobiliario

Date: Fecha de venta

Distance: Distancia al CBD en kilómetros

Regionname: Región general (Oeste, Noroeste, Norte, Noreste, etc.)

Propertycount: Número de propiedades existentes en el suburbio.

Bedroom2 : Número de dormitorios (obtenido de otra fuente)

Bathroom: Número de baños

Car: Número de plazas de aparcamiento

Landsize: Tamaño del terreno en metros cuadrados

BuildingArea: Superficie construida en metros cuadrados

YearBuilt: Año de construcción de la casa

CouncilArea: Área del consejo municipal

Lattitude: Latitud

Longtitude: Longitud

In [3]:
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [6]:
# Seleccion de columnas relevantes: no incluye BuildingArea ni YearBuilt
relevant_columns = ['Suburb','Address','Rooms','Type','Price','Method','SellerG','Date','Distance','Regionname','Propertycount','Bedroom2','Bathroom','Car','Landsize','CouncilArea','Lattitude','Longtitude']
melb_df = melb_df[relevant_columns]
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Regionname     13580 non-null  object
 10  Propertycount  13580 non-null  float64
 11  Bedroom2       13580 non-null  float64
 12  Bathroom       13580 non-null  float64
 13  Car            13518 non-null  float64
 14  Landsize       13580 non-null  float64
 15  CouncilArea    12211 non-null  object
 16  Lattitude      13580 non-null  float64
 17  Longtitude     13580 non-null  float64
dtypes: float64(9), int64(1), object(8)
memory usage: 1.9+ MB

In [8]:
# Verificacion de types en las variables numericas
melb_df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Regionname        object
Propertycount    float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
dtype: object

In [9]:
# Eliminar filas con nulos en Car y CouncilArea
melb_df = melb_df.dropna(subset=['Car','CouncilArea'])
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12211 entries, 0 to 12212
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         12211 non-null  object
 1   Address        12211 non-null  object
 2   Rooms          12211 non-null  int64
 3   Type           12211 non-null  object
 4   Price          12211 non-null  float64
 5   Method         12211 non-null  object
 6   SellerG        12211 non-null  object
 7   Date           12211 non-null  object
 8   Distance       12211 non-null  float64
 9   Regionname     12211 non-null  object
 10  Propertycount  12211 non-null  float64
 11  Bedroom2       12211 non-null  float64
 12  Bathroom       12211 non-null  float64
 13  Car            12211 non-null  float64
 14  Landsize       12211 non-null  float64
 15  CouncilArea    12211 non-null  object
 16  Lattitude      12211 non-null  float64
 17  Longtitude     12211 non-null  float64
dtypes: float64(9), int64(1), object(8)
memory usage: 1.8+ MB

Los tipos de datos parecen estar bien.

In [11]:
# Identificar las variables categoricas del dataset
melb_df.select_dtypes(include=['object'])

,Suburb,Address,Type,Method,SellerG,Date,Regionname,CouncilArea
0,Abbotsford,85 Turner St,h,S,Biggin,3/12/2016,Northern Metropolitan,Yarra
1,Abbotsford,25 Bloomburg St,h,S,Biggin,4/02/2016,Northern Metropolitan,Yarra
2,Abbotsford,5 Charles St,h,SP,Biggin,4/03/2017,Northern Metropolitan,Yarra
3,Abbotsford,40 Federation La,h,PI,Biggin,4/03/2017,Northern Metropolitan,Yarra
4,Abbotsford,55a Park St,h,VB,Nelson,4/06/2016,Northern Metropolitan,Yarra
...,...,...,...,...,...,...,...,...
12208,Williamstown,87 Pasco St,h,S,Jas,29/07/2017,Western Metropolitan,Hobsons Bay
12209,Windsor,201/152 Peel St,u,PI,hockingstuart,29/07/2017,Southern Metropolitan,Stonnington
12210,Wollert,60 Saltlake Bvd,h,S,Stockdale,29/07/2017,Northern Metropolitan,Whittlesea
12211,Yarraville,2 Adeney St,h,SP,hockingstuart,29/07/2017,Western Metropolitan,Maribyrnong
12212,Yarraville,54 Pentland Pde,h,VB,Village,29/07/2017,Western Metropolitan,Maribyrnong

In [12]:
# Ver que datos tiene la variable type
melb_df['Type'].value_counts()

Type
h    8204
u    2962
t    1045
Name: count, dtype: int64

Justifica estudiar categorias:
- Type (3)
- Method (5)
- RegionName (8)
- CouncilArea (33)
- Date (52)

No justifica
- Suburb (308)
- SellerG (253)
- Address (12036)

Posiblemente se pueda reducir las categorias de CouncilArea
Date la agruparia por rangos temporales de manera que resulte en no mas de 5 categorias

In [20]:
melb_df['Date'].value_counts()

Date
27/05/2017    473
3/06/2017     395
12/08/2017    387
17/06/2017    374
27/11/2016    362
29/07/2017    341
4/03/2017     337
25/02/2017    333
24/06/2017    329
10/12/2016    319
22/07/2017    317
8/07/2017     309
18/03/2017    303
15/10/2016    300
15/07/2017    292
12/11/2016    292
3/12/2016     288
8/04/2017     280
1/07/2017     276
19/11/2016    266
20/05/2017    261
18/06/2016    261
28/05/2016    258
13/05/2017    255
8/10/2016     251
7/05/2016     245
17/09/2016    242
24/09/2016    240
28/08/2016    238
10/09/2016    235
16/04/2016    217
29/04/2017    217
4/06/2016     214
27/06/2016    211
3/09/2016     208
22/05/2016    203
7/11/2016     194
14/05/2016    193
22/08/2016    192
30/07/2016    172
6/08/2016     154
16/07/2016    141
6/05/2017     140
22/04/2017    134
26/07/2016    133
13/08/2016    132
23/04/2016    101
11/02/2017     84
12/06/2016     46
11/03/2017     38
4/02/2016      26
28/01/2016      2
Name: count, dtype: int64

In [21]:
# Contar cuantas categorias hay dentro de Date
melb_df['Date'].nunique()

52

## Ejercicio 1: Encoding

1. Seleccionar todas las filas y columnas del conjunto de datos, **excepto** `BuildingArea` y `YearBuilt`.

2. Decidir si elimina algunas filas o columnas en base al análisis de datos faltantes.

3. Hacer un análisis descriptivo de las variables numéricas del conjunto de datos. Todas tienen el tipo `Dtype` correcto asignado? Armar una matriz (array) sólo con las variables numéricas.  

4. Estudiar las variables categóricas del DataFrame. Aplicar una codificación One-hot encoding a las columnas categóricas que crea pertinente. Si lo consideran necesario, pueden reducir el número de categorías únicas de algunas variables. ¿Cómo trataría la variable `Date`? Armar la matriz de variables categóricas codificada.

5. Concatenar la matriz de variables numéricas a la matriz que codifica las variables categóricas resultante del punto anterior.

Algunas opciones:
  1. Utilizar `OneHotEncoder` junto con el parámetro `categories` para las variables categóricas y luego usar `numpy.hstack` para concatenar el resultado con las variables numéricas.
  2. `DictVectorizer` con algunos pasos de pre-proceso previo.

Recordar también que el atributo `pandas.DataFrame.values` permite acceder a la matriz de numpy subyacente a un DataFrame.

## Ejercicio 2: Imputación por KNN

En el teórico se presentó el método `IterativeImputer`, entre otros, para imputar valores faltantes en variables numéricas. Sin embargo, los ejemplos presentados sólo utilizaban algunas variables numéricas presentes en el conjunto de datos. En este ejercicio, utilizaremos la matriz de datos codificada para imputar datos faltantes de manera más precisa.

1. Agregue a la matriz obtenida en el punto anterior las columnas `YearBuilt` y `BuildingArea`.
2. Aplique una instancia de `IterativeImputer` con un estimador `KNeighborsRegressor` para imputar los valores de las variables. ¿Es necesario estandarizar o escalar los datos previamente?
3. Realice un gráfico mostrando la distribución de cada variable antes de ser imputada, y con ambos métodos de imputación.

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.neighbors import KNeighborsRegressor
from sklearn.impute import IterativeImputer

/usr/local/lib/python3.11/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

## Ejercicio 3: Reducción de dimensionalidad.

Utilizando la matriz obtenida en el ejercicio anterior:
1. Aplique `PCA` para obtener $n$ componentes principales de la matriz, donde `n = min(20, X.shape[0])`. ¿Es necesario estandarizar o escalar los datos? Puede decidir si hacer PCA sobre todas las variables o bien seleccionar un subconjunto que crea pertinente.

2. Seleccione las proyecciones de los datos sobre las dos primeras componentes principales (las primeras dos columnas del resultado) para agregar como nuevas características al conjunto de datos.

## Ejercicio 4: Composición del resultado

Transformar nuevamente el conjunto de datos procesado en un `pandas.DataFrame` y guardarlo en un archivo.

Para eso, será necesario recordar el nombre original de cada columna de la matriz, en el orden correcto. Tener en cuenta:
1. El método `OneHotEncoder.get_feature_names` o el atributo `OneHotEncoder.categories_` permiten obtener una lista con los valores de la categoría que le corresponde a cada índice de la matriz.
2. Ninguno de los métodos aplicados intercambia de lugar las columnas o las filas de la matriz.

In [ ]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder

## Ejercicio 5: Documentación

En un documento `.pdf` o `.md` realizar un reporte de las operaciones que realizaron para obtener el conjunto de datos final. Se debe incluir:
  1. Criterios de exclusión (o inclusión) de filas o columnas
  2. Interpretación de las columnas presentes
  2. Todas las transofrmaciones realizadas

Este documento es de uso técnico exclusivamente, y su objetivo es permitir que otres desarrolladores puedan reproducir los mismos pasos y obtener el mismo resultado. Debe ser detallado pero consiso. Por ejemplo:

```
  ## Criterios de exclusión de ejemplos
  1. Se eliminan ejemplos donde el año de construcción es previo a 1900

  ## Características seleccionadas
  ### Características categóricas
  1. Type: tipo de propiedad. 3 valores posibles
  2. ...
  Todas las características categóricas fueron codificadas con un
  método OneHotEncoding utilizando como máximo sus 30 valores más
  frecuentes.
  
  ### Características numéricas
  1. Rooms: Cantidad de habitaciones
  2. Distance: Distancia al centro de la ciudad.
  3. airbnb_mean_price: Se agrega el precio promedio diario de
     publicaciones de la plataforma AirBnB en el mismo código
     postal. [Link al repositorio con datos externos].

  ### Transformaciones:
  1. Todas las características numéricas fueron estandarizadas.
  2. La columna `Suburb` fue imputada utilizando el método ...
  3. Las columnas `YearBuilt` y ... fueron imputadas utilizando el
     algoritmo ...
  4. ...

  ### Datos aumentados
  1. Se agregan las 5 primeras columnas obtenidas a través del
     método de PCA, aplicado sobre el conjunto de datos
     totalmente procesado.
```